Test application -- Guidance -- 3D PPNG
JinraeKim/FlightSims.jl pull request #123
Opened 2021-09-14 21:25 UTC by nhcho91

Nonmanoeuvring Target Interception

2021-09-14 23:08 UTC, JinraeKim commented
A nice try! I'd like to add this example to README.md as an example.

To your question, there are some ways:
1) Using [Closure](https://docs.julialang.org/en/v1/devdocs/functions/#Closures). IMO, this way is simpler.
```julia
function MyController(N)
    return function PPNG(x, params, t)
        # blahblah...
    end
end
```
2) Using `Params` and add an argument `p` to [sim](https://github.com/JinraeKim/FlightSims.jl/blob/master/src/APIs/simulation.jl#L20), similar to `State`. This way is more compatible with DiffEq.jl, i.e., useful when you wanna use the functions from DiffEq.jl I guess.
```
function Params(env::MyEnv)
    return function(N)
        ComponentArrray(N=N)  # not necessary
    end
end

N = 3
params = Params(env)(N)
# ...
prob, df = sim(x0, dynamics!, params;)
```

2021-09-14 23:17 UTC, JinraeKim commented on test/guidance.jl
> +    Δt  = 0.001
It's not actually a simulation parameter.
It is necessary only for saving data.

2021-09-14 23:18 UTC, JinraeKim commented on test/guidance.jl
> +    N
At least for now, `N` in this env does not affect the whole simulation.

2021-09-15 07:05 UTC, JinraeKim reviewed
어느정도 코드 정리가 끝나고 나면, 모델들을 FlightSims.jl 안으로 넣는 캡슐화를 시도해도 좋겠네요 ㅎㅎ

2021-09-15 07:05 UTC, JinraeKim commented on test/guidance.jl
> +function GuidanceLaw(N)
네이밍이 어색한 것 같습니다. 오히려 반대로 GuidanceLaw -> PPNG, PPNG -> guidance_command 정도가 어울릴 것 같아요 (내부의 PPNG 는 외부에서 접근이 안됩니다)

2021-09-15 07:05 UTC, JinraeKim commented on test/guidance.jl
> +struct GuidanceEnv <: AbstractEnv  # AbstractEnv exported from FS
여기도 네이밍이 MissileEnv 혹은 MissileGuidanceEnv 가 좀더 어울릴듯합니다

2021-09-15 07:05 UTC, JinraeKim commented on test/guidance.jl
> +    model_params
이 친구는 필요가 없는 것 같습니다

2021-09-15 11:32 UTC, JinraeKim commented
@nhcho91 확장성을 위해 코드 구조를 바꿔보았습니다만, 시뮬레이션 결과 등의 검증 과정은 거치지 않았습니다.

바꾼 코드는 branch `jinrae-comment` 의 커밋 223dd21 에서 확인 가능합니다.

검토해보시고 괜찮으면 현재 브랜치에 머지 및 수정해주세요 ㅎㅎ

2021-09-15 11:43 UTC, JinraeKim commented
@nhcho91
A few suggestions for the development of missile simulation:
1) restriction of control input (e.g., latax perpendicular to the velocity, actuator saturation)
2) N vs M pursuers & evadors
3) Hi-Fi missile models (e.g., 6-DoF missiles)
4) conventional guidance laws and autopilots (e.g., three-loop autopilot, other variants of PPNG, etc.)

2021-09-15 11:47 UTC, JinraeKim requested changes

2021-09-15 11:47 UTC, JinraeKim commented on test/environments/missiles/pursuer_evador_3d_missile.jl
> +
모든 comment out 된 라인 등을 정리해주세요~

2021-09-15 11:47 UTC, JinraeKim commented on test/pluto_guidance.jl
> +### A Pluto.jl notebook ###
이 파일을 현재 `test/environments/missiles/pursuer_evador_3d_missile.jl` 에 맞게 수정한 뒤,
플루토에서의 interactive 한 결과를 gif 등으로 공유해주실 수 있나요?
FlightSims.jl 의 좋은 예제가 될 것 같습니다.

2021-09-17 08:27 UTC, nhcho91 commented on test/pluto_guidance.jl
> +### A Pluto.jl notebook ###
제가 fork한 branch의 pluto_guidance.jl에 업데이트하였습니다

2021-09-17 12:39 UTC, merged